version: "3"
services:
    app:
        build: .
        command: python main.py
        volumes:
            - .:/opt/app
            - venv:/opt/venv
        ports:
            - 5000:5000
    
volumes:
    app_data:
        driver: local
    venv:
        driver: local